### PR TITLE
Feature/release list

### PR DESCRIPTION
**Pull request by y-asaba**
git daily release listという機能を実装してみました。修正リストを表示する機能になります。
1. git rev-list master..release/xxxx で、commit idを取り出す
2. 各revisionに対して git showを実行
3. git showの結果をparseし、集計する
4. 集計結果を表示

gitdaily.logurlを定義しておくことで、gitwebと連携することもできるようにしています。
仕様について、コードについてなど、ご意見がありましたらフィードバックいただけると幸いです。
よろしくお願いします。

### CODE REVIEW

**Comment by sotarok** [comment]
Thank you for your pull request.

I have some questions:
1. I guess the logurl is some URL template (will be processed by sprintf()) of GitWeb, GitHub or some web based git viewer isn't that?
2. The output format of the logurl section of the release list is a little bit not cool so I committed an alternatives. If you have a clear reason for the format you committed ('= $author:'), please tell me that and I will revert my commit (6f9e7ad1d3eae8dff5e607b3268de72aedb5878f).

Release list is very nice.
I found some bugs of my code and fixed bugs.
Besides, I added an option to set 'logurl' for the config subcommand (de38622f709eef758278e87923da07bd000fadc5).

Best Regards.

# 

無駄に英語にしてみました。

**Comment by y-asaba** [comment]
Thank you for your feedback.

> I guess the logurl is some URL template (will be processed by sprintf()) of GitWeb, GitHub or some web based git viewer isn't that?

That's right. The logurl is a URL template, and git-daily replaces "%s" with a commit checksum.

> The output format of the logurl section of the release list is a little bit not cool so I committed an alternatives. If you have a clear reason for the format you committed ('= $author:'), please tell me that and I will revert my commit (6f9e7ad).

That change looks good to me. I have no concerns.

## Thanks,

onajiku eigo ni shite mimashita.

**Comment by sotarok** [comment]
I merged feature/release_list to develop (a6c101ee8c3a288d2699e8daa652c1e0464d8bca).

I wish you wouldn't create the branch from my master but from develop and wouldn't close your pull request yourself next time.

Thank you.

**Comment by y-asaba** [comment]
Sorry for bothering you. I got it.
Thanks again.

**Pull request closed without merging**
